/**
 *
 * $Id$
 */
package encuesta2.validation;

import encuesta2.Modulo;
import encuesta2.Navegacion;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link encuesta2.Encuesta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EncuestaValidator {
	boolean validate();

	boolean validateModulos(EList<Modulo> value);

	boolean validateNavegacion(EList<Navegacion> value);

	boolean validateNombre(String value);
}
