/**
 *
 * $Id$
 */
package encuesta2.validation;

import encuesta2.Elemento;

/**
 * A sample validator interface for {@link encuesta2.Navegacion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NavegacionValidator {
	boolean validate();

	boolean validateDesde(Elemento value);

	boolean validateHacia(Elemento value);
}
